name: ainv_py310
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - config
  - black
  - flake8
  - isort
  - pip
  - pandas
  - ipykernel
  - matplotlib
  - notebook
  - seaborn
  - scikit-learn
  - scipy
  - pip:
    - python-dotenv
    - evaluate
    - pydantic
    - pydantic-settings
    - instructor
    - openai
    - ollama
    - -e .